name: Deploy Doxygen to Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: philippkarg/smartcard/.github/workflows/build.yml@main
  
  deploy-pages:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Install Doxygen
      run:    |
              sudo apt-get update
              sudo apt-get install graphviz doxygen
      shell: bash

    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html/
      
